#
#	WARNING: Do Not Remove This Section
#
#	$RCSfile: makefile.def,v $
#	$Revision: 1.34 $
#	$Date: 2007/10/24 13:45:18 $
#	$Author: zapreevis $
#	
#	MRMC is a model checker for discrete-time and continuous-time Markov reward models.
#	It supports reward extensions of PCTL and CSL (PRCTL and CSRL), and allows for the
#	automated verification of properties concerning long-run and instantaneous rewards
#	as well as cumulative rewards.
#	
#	Copyright (C) The University of Twente, 2004-2006.
#	Authors: Maneesh Khattri, Ivan Zapreev
#
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of the GNU General Public License
#	as published by the Free Software Foundation; either version 2
#	of the License, or (at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#	Our contacts:
#		Formal Methods and Tools Group, University of Twente,
#		P.O. Box 217, 7500 AE Enschede, The Netherlands,
#		Phone: +31 53 4893767, Fax: +31 53 4893247,
#		E-mail: mrmc@cs.utwente.nl
#
#	Source description: The definitions file, tested with g++ v. 2.7.0
#

#The GSL home directory, just in case you have to set it up
GSL_HOME	= /import/sw/gsl-1.10
CC		= gcc
LEX		= flex
YACC		= yacc -b mrmc_grammar

#The Debug version
#FLAGS		= -O0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -ggdb -g

#The gprof statistics version
#FLAGS		= -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -pg

#The gcov coverage version
#FLAGS		= -O0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fprofile-arcs -ftest-coverage

#The Release version
FLAGS		= -O3 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -L${GSL_HOME}/lib
YFLAGS 	= -d

LIBDIR		= $(MRMC_HOME_DIR)/lib
LIB_A		= $(LIBDIR)/mrmc.a

#Along with the mrmc.a we use GSL library, which has to be preinstalled.
LDFLAGS		= $(LIB_A) -static -lgsl -lgslcblas -lm

STORAGE_SRC_DIR = storage
IO_SRC_DIR = io
PARSER_SRC_DIR = $(IO_SRC_DIR)/parser
ALGORITHMS_SRC_DIR = algorithms
RANDOM_NUMBERS_SRC_DIR = $(ALGORITHMS_SRC_DIR)/random_numbers
LUMPING_SRC_DIR = lumping
MODELCHECKING_SRC_DIR = modelchecking

INCLUDE_DIR	= $(MRMC_HOME_DIR)/include
INCLUDES	= -I$(INCLUDE_DIR) -I$(INCLUDE_DIR)/$(ALGORITHMS_SRC_DIR) -I$(INCLUDE_DIR)/$(LUMPING_SRC_DIR) -I$(INCLUDE_DIR)/$(MODELCHECKING_SRC_DIR) -I$(INCLUDE_DIR)/$(STORAGE_SRC_DIR) -I$(INCLUDE_DIR)/$(IO_SRC_DIR) -I$(INCLUDE_DIR)/$(PARSER_SRC_DIR) -I $(INCLUDE_DIR)/$(RANDOM_NUMBERS_SRC_DIR) -I${GSL_HOME}/include/

EXEC = mrmc

export RM = /bin/rm
export MV = /bin/mv

.SUFFIXES: .c .o .y .l

.c.o:
	$(CC) $(FLAGS) $(INCLUDES) -c $< -o $@

